### ISSUE TITLE
Clarification Question

### ISSUE THREAD

**Issue by christophwille** [Giorgi/EFCore.Visualizer#1]
```
        var blog = sqlServerDb.Blogs
            .OrderBy(b => b.BlogId)
            .First();
```
vs
```
        var query= sqlServerDb.Blogs
            .OrderBy(b => b.BlogId);

        var blog = query.First();
```
The latter one shows the visualizer - this is the expected behavior, correct? (query must be separate from projection)

**Comment by Giorgi** [comment]
Correct, it isn't possible to inspect queries that return a project (First, Max, Sum, etc). For such cases, you can separate queries like in your example but it won't give the real query/plan. When you apply `First`, `Sum`, or other projections the query and hence the plan will be different.
