### ISSUE TITLE
Additional "Works with" targets

### ISSUE THREAD

**Issue by christhecoder** [Giorgi/EFCore.Visualizer#11]
Hi Giorgi, this extension looks great from the description!  I think it will be super useful.  I'd love to give it a go, but it won't install in my Visual Studio 2022 instance.  I suspect it's because it only targets AMD and ARM processors (I've got an Intel processor).  Is there a limitation there, or can additional targets be added so I can install it?  Thanks in advance!

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/1264864/c91c889e-6032-46a1-a97c-d38821666767)

**Comment by Giorgi** [comment]
Which version of VS do you have? 17.8 or 17.9?

**Comment by christhecoder** [comment]
I'm running 17.8.3 at the moment.

**Comment by Giorgi** [comment]
The extension requires VS 17.9 or newer.

**Comment by christhecoder** [comment]
Ah, OK, I'll try updating my VS shortly.  Thanks for your help!

**Comment by Giorgi** [comment]
VS 19.5 was released today.
