### ISSUE TITLE
Incorrect Version of Visual Studio in Manifest file

### ISSUE THREAD

**Issue by waynehamberg** [Giorgi/EFCore.Visualizer#12]
Cripples the project by making the project so it won't work on any version of Visual Studio.  You need to change this from [17.9 to something lower because I just updated my VS2022 and it's at 17.8.6

**Comment by Giorgi** [comment]
Have you tried reading readme?

**Comment by waynehamberg** [comment]
Are you saying that there are features that won't work in the current version of Visual Studio?  Is there a feature that won't work in the current version?  If you want your tool tested and used you should write for the current version.  There are some extensions I would like to add.

**Comment by ErikEJ** [comment]
The tool uses an SDK that only works with VS 17.9 - which is available in preview now.
