### ISSUE TITLE
Error when viewing query plan inside a transaction

### ISSUE THREAD

**Issue by mhguelleh** [Giorgi/EFCore.Visualizer#14]
_I am using Visual Studio version 17.9.0_
_I tried uploading an image file, but `Github` would not accept it_

Here is what I get when I try to use the query plan visualizer:
```
ExecuteNonQuery requires the command to have a transaction
when the connection assigned to the command is in
a pending local transaction. The transaction property of the
command has not been initialized.
```

Here is my query: 
```
using IDbContextTransaction dbContextTransaction = _mainRepositoryWrapperService
    .DbContextService
    .Database
    .BeginTransaction();
try
{
    IQueryable<TableReport> q = _mainRepositoryWrapperService
        .TableReport
        .FindByCondition(f => f.ID == 989);
```

**Comment by mhguelleh** [comment]
It works fine if my query is outside the transaction block.

**Comment by mhguelleh** [comment]
I sometimes have to update a value then execute a join query with the newly created value and some other Database values from different tables.

The query plan visualizer fails to display with the mentioned error if the query is inside the transaction block.

**Comment by Giorgi** [comment]
Please update to the 1.0.4 version and try again.

**Comment by mhguelleh** [comment]
Tested with the latest version 1.0.4 and it works.

Thanks for all your hard work.

**Comment by mhguelleh** [comment]
[Bought you some coffee](https://www.buymeacoffee.com/giorgidev/c/8522368)

**Comment by Giorgi** [comment]
Thanks! Can you leave a review on the marketplace too?

[Write a review](https://marketplace.visualstudio.com/items?itemName=GiorgiDalakishvili.EFCoreVisualizer&ssr=false#review-details)
