### ISSUE TITLE
Could not load file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by Valdas3** [Giorgi/EFCore.Visualizer#17]
I am getting the following error while trying to view the query plan (immediately after clicking on View).
``` 
Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621)
```
VS version is Version 17.9.0. EF Core version is 8.0.0. Any other relevant info I can provide to help resolve the issue?

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/9084046/f3397e3f-3921-44dc-b189-1e323fd28940)

**Comment by Giorgi** [comment]
Does your project reference Newtonsoft.Json? If so which version?

**Comment by Valdas3** [comment]
Newtonsoft.Json is not used in the project.

**Comment by Giorgi** [comment]
You may not be using it directly but some of the NuGet packages that you use could be depending on it. Can you check your [transitive dependencies](https://devblogs.microsoft.com/nuget/introducing-transitive-dependencies-in-visual-studio/)?

**Comment by Valdas3** [comment]
Checked transitive dependencies, it is not in the project that has EF related code. But there is another project in the solution that does use Newtonsoft.Json. These projects do not have common dependencies but maybe it is still somehow related to the issue. 13.0.2 version is used there.

**Comment by Giorgi** [comment]
Thanks for the details. I'll see if I can fix it on my end but I wasn't able to reproduce it even when I added Newtonsoft.Json to my demo project. In the meantime, can you upgrade to Newtonsoft.Json 13.0.3 and see if that helps?

**Comment by ErikEJ** [comment]
Assume you have seen this: https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/

**Comment by Giorgi** [comment]
Thanks, Erik, I haven't seen that article. The NuGet packages that this project depends on have a dependency on the 13.0.3 version so it gets included in the VSIX.

Newtonsoft.Json is used by both the debugger side and the debuggee side so I'm not sure where the conflict is occurring. But according to the [docs](https://learn.microsoft.com/en-us/visualstudio/extensibility/visualstudio.extensibility/debugger-visualizer/debugger-visualizers?view=vs-2022#use-custom-serialization), I should be able to avoid Json serialization altogether if I exchange data by writing to the stream directly.

**Comment by jogibear9988** [comment]
The https://www.nuget.org/packages/Microsoft.VisualStudio.SDK assembly adds the NewtonsoftJson dependecy with V13.0.3

a older version of it <17.6.36389 does not yet have this dependency.

Don't know if you could use it.

**Comment by Giorgi** [comment]
@Valdas3 Can you upgrade to 1.0.5 and see if it solves the issue?

**Comment by Valdas3** [comment]
Thanks, I no longer get the issue. But I noticed that for queries that take more time, I get an "Evaluation timed out" error. Is the time-out period something that can be configured?
![image](https://github.com/Giorgi/EFCore.Visualizer/assets/9084046/2991a1be-0e76-47f9-9fce-9b1ab5ef21ee)

**Comment by Giorgi** [comment]
I'm not sure but I'll check. How long does it take approximately for the error to pop up?
