### ISSUE TITLE
View section does not appear.

### ISSUE THREAD

**Issue by BlueGreenWorld** [Giorgi/EFCore.Visualizer#21]
I am using Visual Studio 17.9.0 and My Project has Microsoft.EntityFrameworkCore 8.0.1
Also installed the EFCore.Visualizer plugin. But the view section does not appear.

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/3757617/2727ebcb-aa50-4bee-90fa-4755c1be76b2)

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/3757617/d7006a9a-3747-4cb4-aa28-b19686f05c96)

**Comment by Giorgi** [comment]
You are trying to inspect a `List<>` variable. This extension supports inspection `IQueryable<>` variables. You can't inspect intermediate values in VS.

**Comment by BlueGreenWorld** [comment]
Yes, tested, is ok.... Thnx... 
![image](https://github.com/Giorgi/EFCore.Visualizer/assets/3757617/429bb468-ab5b-466d-bc88-6460a514627b)

**Comment by AlvarHM** [comment]
![Image](https://github.com/user-attachments/assets/33794135-4ecb-40f2-8f04-925b660e76f2)
It does not work

**Comment by Giorgi** [comment]
Can you try if it works without the `AsQueryable` call?

**Comment by AlvarLucasCordova** [comment]
![Image](https://github.com/user-attachments/assets/ab229331-6237-44aa-b97e-579c5b98cb55)
I have tried many queries but they still don't work.
