### ISSUE TITLE
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational

### ISSUE THREAD

**Issue by ctolkien** [Giorgi/EFCore.Visualizer#24]
---------------------------
Error
---------------------------
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
![image](https://github.com/Giorgi/EFCore.Visualizer/assets/515955/3dcf5127-d5b6-4cb5-a56c-e9aa666432b7)

This is a .NET6 app, I'm not sure if I have .net7 installed.

**Comment by shamim4063** [comment]
Got same issue with EntityFrameworkCore 6.0.1

**Comment by ErikEJ** [comment]
@shamim4063 The extension only supports EF Core 7 or newer

**Comment by Giorgi** [comment]
Closing due to no response from the author. The extension requires EF Core 7 or newer to work.
