### ISSUE TITLE
SQL Server query plan does not render correctly when the window is resized

### ISSUE THREAD

**Issue by KrisVandermotten** [Giorgi/EFCore.Visualizer#26]
For example:

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/273237/682f71c0-5a54-47d6-99ff-2206f9475deb)

Also, it would be good if the window would remember its last size.

**Comment by Giorgi** [comment]
Thanks, will be fixed in the next release.

**Comment by Giorgi** [comment]
@KrisVandermotten The fix is now live.
