### ISSUE TITLE
Unable to use query plan visualizer

### ISSUE THREAD

**Issue by Varorbc** [Giorgi/EFCore.Visualizer#27]
When I move my mouse over the where condition, I cannot use the query plan expression. I must define a variable to work well, which will cause a lot of inconvenience in practical use

![test](https://github.com/Giorgi/EFCore.Visualizer/assets/5714438/1439fe4f-2966-4da1-8375-4b52fcc37ed6)

**Comment by Giorgi** [comment]
That's how VS Debugger works and I cannot do anything about it.
