### ISSUE TITLE
Two error popups when I try to visualize the query

### ISSUE THREAD

**Issue by jrichview** [Giorgi/EFCore.Visualizer#32]
Installed it, ran my console app built with EF Core 8, hovered over my query and popped up the visualizer, but received two error popups:

"Cannot evaluate expression since the function evaluation requires all threads to run." 

"To prevent an unsafe abort when evaluating the function 'Microsoft.VisualStudio.DebuggerVisualizers.DebuggeeSide.Impl.ClrCustomVisualizerDebuggeeHost.TransferData' all threads were allowed to run. This may have changed the state of the process and any breakpoints encountered have been skipped."

**Comment by Giorgi** [comment]
@jrichview Is your project using Application Insights?

**Comment by jrichview** [comment]
Yes

**Comment by Giorgi** [comment]
Check the [Known Issues](https://github.com/Giorgi/EFCore.Visualizer#known-issues) section in the ReadMe
