### ISSUE TITLE
Possibility for < VS17. 9

### ISSUE THREAD

**Issue by MichaelVanHouHei** [Giorgi/EFCore.Visualizer#39]
Its a nice project, extension that meet my current scenario.
Just woundering if could be support widely VS version such that [17.0,18.0)?

**Comment by ErikEJ** [comment]
@MichaelVanHouHei Nope, it **needs** 17.9 or later, as clearly documented

**Comment by MichaelVanHouHei** [comment]
> @MichaelVanHouHei Nope, it **needs** 17.9 or later, as clearly documented

Yea. Just read the source code as because of  new framework VisualStudio. Extensionabily. 
Thanks.
