### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by casually-creative** [Giorgi/EFCore.Visualizer#8]
7/02/2024 9:37:27 - 	Extension is not signed.
7/02/2024 9:37:27 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   bij VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bij VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bij VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bij VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bij VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bij VSIXInstaller.App.Initialize()
   bij System.Threading.Tasks.Task`1.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()

**Comment by Giorgi** [comment]
Which version of VS 2022 do you have? **The extension requires 17.9 or newer.**

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/580749/6f2ed5be-b9b4-4379-bd54-2e97734716a0)

**Comment by casually-creative** [comment]
I was on 17.8.5, but even after upgrading to 17.9.0 it still doesn't work.

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/5587999/6e1aa367-35ff-4eaf-8f6e-e40d1c825263)

**Comment by casually-creative** [comment]
I'm on the latest version that is available to me: 17.8.6

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/5587999/5fed6a3e-b03b-483a-b5f1-bfdabd07e93a)

**Comment by Giorgi** [comment]
17.9 is in preview. You need to either install a preview version or wait until it is released to the stable channel.

**Comment by Giorgi** [comment]
VS 19.5 was released today.
