### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by mjviana** [Giorgi/EFCore.Visualizer#9]
Hi

I'm not able to install this extension.
Currently I have VS2019 and VS2022

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/31926338/446db9b9-130f-456b-8951-639523a72d80)

**Comment by Giorgi** [comment]
Which version of VS 2022 do you have? 17.8.x or 17.9.x?

**Comment by Giorgi** [comment]
Did you read me the Readme?
